import type { Locale } from "@/lib/i18n-config";

export interface MarketSeoProfile {
  keywords: string[];
  applicationCategory: string;
  featureList: string[];
}

function profile(keywords: string[], featureList: string[]): MarketSeoProfile {
  return { keywords, applicationCategory: "GameApplication", featureList };
}

const PROFILES: Record<Locale, MarketSeoProfile> = {
  en: profile(
    [
      "word game app",
      "best word game apps",
      "party game app",
      "taboo game",
      "forbidden words game",
      "how to play taboo",
      "heads up game",
      "charades app",
      "how to play charades",
      "heads up charades",
      "word guessing game",
      "mobile party games",
      "AI deck builder",
      "free word game",
      "best mobile word games",
      "how to play heads up charades",
      "party word games",
    ],
    [
      "Taboo (Forbidden Words) mode",
      "Heads Up charades mode",
      "AI custom deck creation",
      "Free starter deck",
      "17 languages",
      "No ads",
      "No subscription",
      "Word difficulty multipliers",
    ],
  ),
  tr: profile(
    [
      "tabu nasıl oynanır",
      "tabu oyunu",
      "tabu kelime oyunu",
      "yasaklı kelimeler",
      "yasaklı kelimeler nasıl oynanır",
      "alnında tahmin",
      "alnında tahmin nasıl oynanır",
      "heads up charades",
      "kelime oyunu",
      "kelime tahmin oyunu",
      "en iyi kelime oyunu uygulaması",
      "en iyi parti oyunu uygulaması",
      "parti oyunu uygulaması",
      "mobil kelime oyunu",
      "yapay zeka deste",
      "en iyi mobil kelime oyunu",
      "heads up nasıl oynanır",
      "charades oyunu",
    ],
    [
      "Yasaklı Kelimeler (Tabu) modu",
      "Alnında Tahmin (Heads Up) modu",
      "Yapay zeka ile deste oluşturma",
      "Ücretsiz Tadado Mix destesi",
      "17 dil desteği",
      "Reklamsız",
      "Abonelik yok",
      "Kelime zorluk çarpanları",
    ],
  ),
  es: profile(
    [
      "juego de tabú",
      "cómo jugar tabú",
      "heads up",
      "charadas",
      "mejor app juegos de palabras",
      "juego de fiesta móvil",
      "adivina la palabra",
      "juego de palabras gratis",
      "mazos con IA",
      "juego de adivinanzas",
    ],
    [
      "Modo Tabú (Palabras Prohibidas)",
      "Modo Heads Up charadas",
      "Creación de mazos con IA",
      "Mazo Tadado Mix gratis",
      "17 idiomas",
      "Sin anuncios",
      "Sin suscripción",
    ],
  ),
  de: profile(
    [
      "tabu spiel",
      "tabu app",
      "wie spielt man tabu",
      "heads up spiel",
      "scharade app",
      "beste wortspiel app",
      "partyspiel app",
      "wort ratespiel",
      "ki deck erstellen",
      "kostenloses wortspiel",
    ],
    [
      "Tabu (Verbotene Wörter) Modus",
      "Heads Up Scharade Modus",
      "KI-Deck-Erstellung",
      "Gratis Tadado Mix Deck",
      "17 Sprachen",
      "Keine Werbung",
      "Kein Abo",
    ],
  ),
  fr: profile(
    [
      "jeu tabou",
      "comment jouer au tabou",
      "heads up",
      "charades",
      "meilleure app jeu de mots",
      "jeu de fête mobile",
      "jeu de devinettes",
      "jeu de mots gratuit",
      "deck IA",
      "jeu de mots soirée",
    ],
    [
      "Mode Tabou (Mots Interdits)",
      "Mode Heads Up charades",
      "Création de deck IA",
      "Deck Tadado Mix gratuit",
      "17 langues",
      "Sans pub",
      "Sans abonnement",
    ],
  ),
  "pt-BR": profile(
    [
      "jogo de tabu",
      "como jogar tabu",
      "heads up",
      "charades",
      "melhor app jogo de palavras",
      "jogo de festa mobile",
      "adivinhe a palavra",
      "jogo de palavras grátis",
      "baralho com IA",
      "jogo de adivinhação",
    ],
    [
      "Modo Tabu (Palavras Proibidas)",
      "Modo Heads Up charades",
      "Criação de baralho com IA",
      "Baralho Tadado Mix grátis",
      "17 idiomas",
      "Sem anúncios",
      "Sem assinatura",
    ],
  ),
  it: profile(
    [
      "gioco tabù",
      "come giocare a tabù",
      "heads up",
      "charades",
      "migliore app giochi di parole",
      "gioco di festa mobile",
      "indovina la parola",
      "gioco di parole gratis",
      "mazzo IA",
      "gioco di indovinelli",
    ],
    [
      "Modalità Tabù (Parole Proibite)",
      "Modalità Heads Up charades",
      "Creazione mazzo IA",
      "Mazzo Tadado Mix gratuito",
      "17 lingue",
      "Senza pubblicità",
      "Nessun abbonamento",
    ],
  ),
  ja: profile(
    [
      "タブーゲーム",
      "タブー 遊び方",
      "ヘッズアップ",
      "シャレード",
      "ワードゲーム アプリ",
      "パーティーゲーム",
      "言葉当てゲーム",
      "無料 ワードゲーム",
      "AI デッキ",
      "モバイル パーティーゲーム",
    ],
    [
      "タブー（禁止ワード）モード",
      "ヘッズアップ シャレードモード",
      "AIデッキ作成",
      "無料Tadado Mixデッキ",
      "17言語対応",
      "広告なし",
      "サブスクなし",
    ],
  ),
  ko: profile(
    [
      "금지어 게임",
      "타부 게임",
      "헤즈업",
      "몸으로 말해요",
      "단어 게임 앱",
      "파티 게임",
      "단어 맞히기",
      "무료 단어 게임",
      "AI 덱",
      "모바일 파티 게임",
    ],
    [
      "금지어(타부) 모드",
      "헤즈업 몸말 모드",
      "AI 덱 생성",
      "무료 Tadado Mix 덱",
      "17개 언어",
      "광고 없음",
      "구독 없음",
    ],
  ),
  zh: profile(
    [
      "禁忌词游戏",
      "怎么玩禁忌词",
      "heads up",
      "猜词游戏",
      "最好单词游戏app",
      "派对游戏",
      "词语猜测",
      "免费单词游戏",
      "AI卡组",
      "手机派对游戏",
    ],
    [
      "禁忌词（Taboo）模式",
      "Heads Up 猜词模式",
      "AI卡组创建",
      "免费Tadado Mix卡组",
      "17种语言",
      "无广告",
      "无订阅",
    ],
  ),
  ru: profile(
    [
      "игра табу",
      "как играть в табу",
      "heads up",
      "шарады",
      "лучшее приложение словесных игр",
      "игра для вечеринки",
      "угадай слово",
      "бесплатная словесная игра",
      "колода ИИ",
      "мобильная игра для компании",
    ],
    [
      "Режим Табу (Запретные слова)",
      "Режим Heads Up шарады",
      "Создание колоды ИИ",
      "Бесплатная колода Tadado Mix",
      "17 языков",
      "Без рекламы",
      "Без подписки",
    ],
  ),
  ar: profile(
    [
      "لعبة تابو",
      "كيف تلعب تابو",
      "heads up",
      "تخمين الكلمات",
      "أفضل تطبيق ألعاب كلمات",
      "لعبة حفلات",
      "لعبة كلمات مجانية",
      "مجموعة ذكاء اصطناعي",
      "لعبة تخمين",
      "ألعاب حفلات موبايل",
    ],
    [
      "وضع تابو (الكلمات المحظورة)",
      "وضع Heads Up",
      "إنشاء مجموعة بالذكاء الاصطناعي",
      "مجموعة Tadado Mix مجانية",
      "17 لغة",
      "بدون إعلانات",
      "بدون اشتراك",
    ],
  ),
  hi: profile(
    [
      "taboo game",
      "heads up game",
      "charades app",
      "best word game app",
      "party game app",
      "word guessing game",
      "free word game",
      "AI deck",
      "mobile party game",
      "शब्द खेल ऐप",
    ],
    [
      "Taboo (Forbidden Words) मोड",
      "Heads Up charades मोड",
      "AI डेक निर्माण",
      "मुफ्त Tadado Mix डेक",
      "17 भाषाएँ",
      "कोई विज्ञापन नहीं",
      "कोई सब्सक्रिप्शन नहीं",
    ],
  ),
  id: profile(
    [
      "game tabu",
      "cara main tabu",
      "heads up",
      "charades",
      "aplikasi permainan kata terbaik",
      "game pesta mobile",
      "tebak kata",
      "permainan kata gratis",
      "deste AI",
      "game tebak kata",
    ],
    [
      "Mode Tabu (Kata Terlarang)",
      "Mode Heads Up charades",
      "Pembuatan deste AI",
      "Deste Tadado Mix gratis",
      "17 bahasa",
      "Tanpa iklan",
      "Tanpa langganan",
    ],
  ),
  vi: profile(
    [
      "game taboo",
      "cách chơi taboo",
      "heads up",
      "charades",
      "app trò chơi đoán từ tốt nhất",
      "game tiệc tùng",
      "đoán từ",
      "trò chơi từ miễn phí",
      "bộ bài AI",
      "game đoán từ mobile",
    ],
    [
      "Chế độ Taboo (Từ cấm)",
      "Chế độ Heads Up charades",
      "Tạo bộ bài AI",
      "Bộ bài Tadado Mix miễn phí",
      "17 ngôn ngữ",
      "Không quảng cáo",
      "Không đăng ký",
    ],
  ),
  pl: profile(
    [
      "gra tabu",
      "jak grać w tabu",
      "heads up",
      "kalambury",
      "najlepsza aplikacja gier słownych",
      "gra imprezowa",
      "zgadnij słowo",
      "darmowa gra słowna",
      "talia AI",
      "gra słowna mobile",
    ],
    [
      "Tryb Tabu (Zakazane słowa)",
      "Tryb Heads Up kalambury",
      "Tworzenie talii AI",
      "Darmowa talia Tadado Mix",
      "17 języków",
      "Bez reklam",
      "Bez subskrypcji",
    ],
  ),
  el: profile(
    [
      "παιχνίδι taboo",
      "πώς παίζεται το taboo",
      "heads up",
      "χαράδες",
      "καλύτερη εφαρμογή παιχνιδιού λέξεων",
      "παιχνίδι πάρτι",
      "μάντεψε τη λέξη",
      "δωρεάν παιχνίδι λέξεων",
      "τράπουλα AI",
      "mobile party game",
    ],
    [
      "Λειτουργία Taboo (Απαγορευμένες λέξεις)",
      "Λειτουργία Heads Up χαράδες",
      "Δημιουργία τράπουλας AI",
      "Δωρεάν τράπουλα Tadado Mix",
      "17 γλώσσες",
      "Χωρίς διαφημίσεις",
      "Χωρίς συνδρομή",
    ],
  ),
};

export function getMarketSeoProfile(locale: Locale): MarketSeoProfile {
  return PROFILES[locale];
}

export function getKeywordsString(locale: Locale): string {
  return getMarketSeoProfile(locale).keywords.join(", ");
}
